Update 0-transfer_file

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -1,7 +1,23 @@
 #!/usr/bin/env bash
 # Bash script that transfers a file from our client to a server
-if [ "$#" -lt 4]; then 
-    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY";
+if [ "$#" -lt 4 ]; then
+  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+  exit 1
+fi
+
+# Assign parameters to variables
+FILE_PATH="$1"
+SERVER_IP="$2"
+USERNAME="$3"
+SSH_KEY_PATH="$4"
+
+# Transfer file using scp
+scp -o StrictHostKeyChecking=no -i "$SSH_KEY_PATH" "$FILE_PATH" "$USERNAME@$SERVER_IP":~
+
+# Check if transfer was successful
+if [ "$?" -eq 0 ]; then
+  echo "File transfer successful"
 else
-    scp -o "StrictHostKeyChecking=no" -i "$4" "$1" "$3@$2":~/;
-fi 
+  echo "File transfer failed"
+fi
+
